@startuml ColorFlow
title: Color Flow for SonarQube stats

start

if (IsDomainSize?) then (yes)
  -[#gray]-> GrayColor;
else (no)
  if (IsQualitative) then (yes)
    if (IsHigherBetter) then (yes)
      if (isHigherOrEqualThanWorst) then (yes)
        -[#green]-> GreenColor;
      else (no)
        if (finalIsHigherThanTheBest) then (yes)
          -[#orange]-> OrangeColor;
        else (no)
          -[#red]-> RedColor;
        endif
      endif
    else (no)
      if (IsLowerOrEqualThanBest) then (yes)
        -[#green]-> GreenColor;
      else (no)
        if (finalLowerThanWorst) then (yes)
          -[#orange]-> OrangeColor;
        else (no)
          -[#red]-> RedColor;
        endif
      endif
    endif
  else (no)
    if (IsContainingMetric) then (yes)
      :finalBestValueColor;
      note right
        This finalBest contains too much code
        and should be splitted
        ====
        * can lightGray
        * can yellowGreen
        * can Red
      end note
    else (no)
      -[#gray]-> GrayColor;
    endif
  endif
endif
@enduml